In [54]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from scipy.fftpack import fft, ifft
import matplotlib.pyplot as plt
from sklearn import linear_model
from sklearn.metrics import precision_recall_curve
from sklearn.metrics import confusion_matrix
import warnings
warnings.filterwarnings("ignore")
from sklearn import metrics
from sklearn.model_selection import ParameterGrid
from sklearn.linear_model import SGDClassifier
from sklearn.metrics import roc_auc_score
import parfit.parfit as pf
from sklearn.metrics import mean_squared_error

In [46]:
clf =  linear_model.SGDClassifier(loss = "log", penalty = 'l2', alpha = 1e-1)

In [49]:
for i in range (1,40):
    data = pd.read_csv(r"C:\Users\Piotrek\Documents\projektIO\Dane\Dane\Nowy Folder\dane\l{}.csv".format(i),header = None) 
    datalabel = pd.read_csv(r"C:\Users\Piotrek\Documents\projektIO\Dane\Dane\Nowy Folder\labele\{}_label.csv".format(i),header = None)
    Y = datalabel.iloc[:,[0]]
    x = data.iloc[:,[19,20,21,22,24,25,33,38]]
    Y = Y.replace(0.5, 1)
    clf.partial_fit(x, Y.values.ravel(), classes=[0, 1])

1.0
0.7475142420086507
1.0
0.9386163167729171
1.0
1.0
1.0
0.9657097912983634
1.0
0.9356162307292569
1.0
1.0
0.998038704192149
0.9990813943261441
0.9684939033657162
1.0
1.0
0.9788173858416114
0.9679542523967035
1.0
1.0
0.9747264568913047
1.0
1.0
0.978080437406103
0.9576165455025313
1.0
0.9832954580829935
1.0
1.0
1.0


In [55]:
sum1 = 0
sum2 = 0
sum3 = 0
sum4 = 0
for i in range (1,17):
    datat = pd.read_csv(r"C:\Users\Piotrek\Documents\projektIO\Dane\Dane\danetest\{}.csv".format(i),header = None) 
    datalabelt = pd.read_csv(r"C:\Users\Piotrek\Documents\projektIO\Dane\Dane\danetest\labels\{}_label.csv".format(i),header = None)
    Yt = datalabelt.iloc[:,[0]]
    xt = datat.iloc[:,[19,20,21,22,24,25,33,38]]
    Yt = Yt.replace(0.5, 1)
    clf.score(xt,Yt.values.ravel())
    y_pred = clf.predict(xt)
    sum1 = sum1 + metrics.accuracy_score(Yt, y_pred)
    sum2 = sum2 + metrics.recall_score(Yt, y_pred)
    sum3 = sum3 + metrics.precision_score(Yt, y_pred)
    sum4 = sum4 + mean_squared_error(Yt, y_pred)

In [230]:
clf.coef_

array([[-1.29043233e+03, -1.92596886e+00, -3.16159715e+03,
        -1.07679133e-02,  4.80477805e+03, -1.92697089e+00,
        -3.40026949e+04, -2.66949521e+04]])

In [231]:
clf.intercept_

array([-148.92790738])

In [57]:
accuracy = sum1 / 17
accuracy

0.8875985821989939

In [58]:
recall = sum2 / 17
recall

0.0

In [43]:
conf = confusion_matrix(Yt, y_pred)
conf

array([[402292,      0],
       [478906,      0]], dtype=int64)

In [59]:
precision = sum3 / 17
precision

0.0

In [60]:
mse = sum4 / 17
mse

0.02149232689191522